export const rules = {
  helmand: {
    EASY_WOUND_STABILIZATION_TIME: 10 * 60 * 1000,
    SERIOUS_WOUND_STABILIZATION_TIME: 10 * 60 * 1000,
    EASY_WOUND_BLEEDING_TIME_AFTER_FIRST_AID: 30 * 60 * 1000,
    SERIOUS_WOUND_BLEEDING_TIME_AFTER_FIRST_AID: 20 * 60 * 1000,
    STABILIZATION_TYPE: 'add',
    FIRST_AID_POINTS: 3,
    CONTUSION_TIME: 10 * 1000,
    SERIOUS_WOUND_RESTRICTIONS: '<p>- Can only ask for help</p>',
    HAND_WOUND_RESTRICTIONS: '<p>- Only one handed fire</p>',
    TWO_HANDS_WOUND_RESTRICTIONS: '<p>- No guns</p><p>- No self first aid</p>',
    HANDS_BANDAGE_RESTRICTIONS: '<p>- Only one handed fire</p>',
    LEG_WOUND_RESTRICTIONS: '<p>- Only one leg walking</p>',
    ONE_LEG_BANDAGE_RESTRICTIONS: '<p>- Only one leg walking</p>',
    TWO_LEGS_BANDAGE_RESTRICTIONS: '<p>- Can only crawl</p>',
    TWO_LEGS_WOUND_RESTRICTIONS: '<p>- Can only crawl</p>',
  },
  desertThunder: {
    EASY_WOUND_STABILIZATION_TIME: 5 * 60 * 1000,
    SERIOUS_WOUND_STABILIZATION_TIME: 15 * 60 * 1000,
    EASY_WOUND_BLEEDING_TIME_AFTER_FIRST_AID: 60 * 60 * 1000,
    SERIOUS_WOUND_BLEEDING_TIME_AFTER_FIRST_AID: 15 * 60 * 1000,
    EVACUATION_TIME: 60 * 60 * 1000,
    WOUNDS_CAN_BE_STABILIZED: true,
    STABILIZATION_TYPE: 'reset',
    FIRST_AID_POINTS: 1,
    CONTUSION_TIME: 5 * 60 * 1000,
    SERIOUS_WOUND_RESTRICTIONS: '<p>- Can only ask for help</p>',
    HAND_WOUND_RESTRICTIONS: '<p>- No guns</p>',
    TWO_HANDS_WOUND_RESTRICTIONS: '<p>- No guns</p><p>- No self first aid</p>',
    HANDS_BANDAGE_RESTRICTIONS: '<p>- Only one handed fire</p>',
    LEG_WOUND_RESTRICTIONS: '<p>- No movement</p>',
    ONE_LEG_BANDAGE_RESTRICTIONS: '<p>- Can\'t run</p>',
    TWO_LEGS_BANDAGE_RESTRICTIONS: '<p>- Can\'t run</p>',
    TWO_LEGS_WOUND_RESTRICTIONS: '<p>- No movement</p>',
  },
};
